name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-site:v1 .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-site:v1

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-site:v1
          docker stop portfolio || true
          docker rm portfolio || true
          docker run -d -p 80:8000 --name portfolio ${{ secrets.DOCKER_USERNAME }}/portfolio-site:v1
